"""Local Qwen-based source generation for restricted shadow tools."""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional


BASIC_TOOL_TEMPLATE = '''"""
Tool: {name}
Generated by: Shadow Engine
Confidence: {score}
Date: {date}

Description: {description}
"""

import json

def run(params: dict) -> dict:
    try:
        result = execute_task(params)
        return {{"success": True, "result": str(result), "error": None}}
    except Exception as exc:
        return {{"success": False, "result": None, "error": str(exc)}}

{body}

if __name__ == "__main__":
    print(json.dumps(run({{}}), ensure_ascii=False))
'''


class ToolGenerator:
    """Generates only the task body; the safe outer contract is ours."""

    def __init__(self, directory: Path | str, *, settings: Any = None,
                 generate: Optional[Callable[[str], str]] = None) -> None:
        self.directory = Path(directory)
        self.directory.mkdir(parents=True, exist_ok=True)
        self._settings = settings
        self._generate = generate

    def prompt(self, *, description: str, params: dict[str, Any], expected_output: str,
               examples: str) -> str:
        return (
            "Ты — генератор инструментов для ATLAS. Напиши Python-функцию, которая:\n\n"
            f"Задача: {description}\nВходные параметры: {params}\nВыход: {expected_output}\n\n"
            "Требования:\n- Используй только стандартную библиотеку Python\n"
            "- Не лезь в системные папки без явного пути\n- Обрабатывай ошибки\n"
            "- Верни JSON с success/result/error\n\n"
            f"Примеры существующих инструментов:\n{examples}\n\n"
            "Напиши только код функции execute_task(params), без объяснений."
        )

    def generate(self, *, name: str, description: str, confidence: float,
                 params: dict[str, Any], expected_output: str, examples: str) -> str:
        prompt = self.prompt(description=description, params=params,
                             expected_output=expected_output, examples=examples)
        body = self._clean(self._call_local_model(prompt))
        if "def execute_task" not in body:
            raise ValueError("локальная модель не вернула execute_task(params)")
        return self.wrap(name=name, description=description, confidence=confidence, body=body)

    @staticmethod
    def wrap(*, name: str, description: str, confidence: float, body: str) -> str:
        return BASIC_TOOL_TEMPLATE.format(
            name=re.sub(r"[^a-zA-Z0-9_]", "_", name), description=description[:500],
            score=f"{confidence:.0%}", date=datetime.now(timezone.utc).date().isoformat(),
            body=body.strip(),
        )

    def _call_local_model(self, prompt: str) -> str:
        if self._generate is not None:
            return self._generate(prompt)
        if self._settings is None:
            raise RuntimeError("локальная Qwen3-1.7B для Shadow Engine не настроена")
        from core.llm.local_qwen import LocalQwenBackend
        shadow = getattr(self._settings, "shadow", None)
        path = getattr(shadow, "resolved_code_model_path", None)
        if path is None:
            raise RuntimeError("не задан путь к Qwen3-1.7B")
        backend = LocalQwenBackend(path, model_id="qwen3-1.7b-shadow", temperature=0.15,
                                   max_tokens=1200, n_ctx=4096)
        return backend.direct(prompt, temperature=0.15, max_tokens=1200)

    @staticmethod
    def _clean(code: str) -> str:
        text = (code or "").strip()
        text = re.sub(r"^```(?:python)?\s*", "", text, flags=re.IGNORECASE)
        return re.sub(r"\s*```$", "", text).strip()
